### ISSUE TITLE
bugs in data_prep

### ISSUE THREAD

**Issue by cuge1995** [QingyongHu/RandLA-Net#104]
./data/S3DIS/Stanford3dDataset_v1.2_Aligned_Version/Area_1/conferenceRoom_1/Annotations
Traceback (most recent call last):
  File "utils/data_prepare_s3dis.py", line 80, in <module>
    convert_pc2ply(annotation_path, join(original_pc_folder, out_file_name))
  File "utils/data_prepare_s3dis.py", line 47, in convert_pc2ply
    pc_label = np.concatenate(data_list, 0)
ValueError: need at least one array to concatenate

**Comment by cuge1995** [comment]
solved by ' sudo chmod -R 777 Stanford3dDataset_v1.2_Aligned_Version/ '

**Comment by wakasu** [comment]
> solved by ' sudo chmod -R 777 Stanford3dDataset_v1.2_Aligned_Version/ '

Hi there!
have tried your solution but still its giving the same error
what might i be doing wrong. 
Any help would be appreciated

**Comment by youssef962** [comment]
same error!
Have you fixed it? @wakasu
