### ISSUE TITLE
 helper_tool.py——get_class_weights()函数中S3DIS的权重是怎么来的？ 

### ISSUE THREAD

**Issue by suyanfei** [QingyongHu/RandLA-Net#108]
# pre-calculate the number of points in each category 
if dataset_name is 'S3DIS':
            num_per_class = np.array([3370714, 2856755, 4919229, 318158, 375640, 478001, 974733,
                                      650464, 791496, 88727, 1284130, 229758, 2272837], dtype=np.int32)
你好，请问数组中的数字是怎么来的呢？，我看您写的备注是每一类点的数量，但是我统计了6个区域中每个类的点数量，可是没有一区域符合上面的数值。谢谢！

**Comment by QingyongHu** [comment]
Hi @suyanfei, thanks for your interest in our work!

非常抱歉没有及时回复，因为我们在一开始对点云进行了grid_sampling，所以这个值是根据grid_sampling以后的sub_area得到的。希望能解答你的问题~

**Comment by suyanfei** [comment]
> Hi @suyanfei, thanks for your interest in our work!
> 
> 非常抱歉没有及时回复，因为我们在一开始对点云进行了grid_sampling，所以这个值是根据grid_sampling以后的sub_area得到的。希望能解答你的问题~

**Comment by suyanfei** [comment]
OK，@QingyongHu，明白了，多谢啦！
