### ISSUE TITLE
，对与semanticKITTI数据集，运行一次网络能否进行单帧激光雷达点云数据的准确分割

### ISSUE THREAD

**Issue by qiaoqiaodefengle187** [QingyongHu/RandLA-Net#109]
@QingyongHu 胡博你好，代码中，网络对semanticKITTI数据集进行测试的时候，每帧激光点云数据被运行了多次，最终的结果是多次预测结果的滑动平均值（不知道我的理解是否正确），如果对单帧数据只通过网络进行一次预测，能否达到比较好的分割效果呢？（之前用您提供的预训练模型测试了一下，感觉单次分割效果不太好呢，不知道是不是我代码有问题）

**Comment by QingyongHu** [comment]
Hi @qiaoqiaodefengle187 ，我们运行多次的原因是因为每帧点云的点的数量不是一样的多，但是test时候我们每个batch的点数是一样的大小，所以对于每帧点云我们需要测试几次以覆盖点云中所有的点。你说的单次分割不知道是否改变了num_points？如果没有的话相当于很多点云中的点并没有被inference到，所以效果不好。另一种方式是将batch_size改成1，num_points对应于所有的点数，这样效果应该会更好一些。

希望能够解答你的问题！

**Comment by GriffinZhao** [comment]
@QingyongHu 胡博士你好，我也在尝试构建一个单帧推理服务，在使用kitti预训练模型对单帧数据值通过网络进行一次预测情况下，我得到的推理结果也很差，结果无法识别物体边界，临近点标签不一致且杂乱，像雪花图一样。
您提到将batch_size改为1，并改变num_points，想请教一下具体如何修改呢？如果num_points的值大于当前帧实际点数会报"k must be less than or equal to the number of training points"错误，如果小于当前帧点数，在batch_size为1的情况下则会使得输出标签数仅等于num_points，而不能与实际点数对齐。
希望能获得帮助，谢谢！
附图为我当前单帧推理结果示例。
![微信截图_20250111002943](https://github.com/user-attachments/assets/2e944c0d-ff3d-4f30-b99d-8cb948000cb0)
