### ISSUE TITLE
question about valid_labels

### ISSUE THREAD

**Issue by LiDaiY** [QingyongHu/RandLA-Net#111]
你好，我想问下，在训练semantic3d时，为什么要使用valid_labels 去算损失，而不是使用valid_labels_init ，
比如:
```
ignored_label_inds = [0]
labels= [2,1,0,1,5,5,0,4,1]
```
那么 Reduce label values in the range of logit shape之后，
https://github.com/QingyongHu/RandLA-Net/blob/3aafa161f32730fa1a9bbd63d06afe8e18ce9ab9/RandLANet.py#L71
可以得到:
```
valid_labels_init =[2,1,1,5,5,4,1]
valid_labels =[1,0,0,4,4,3,0]
```
在这里，我比较困惑，为什么不直接把valid_labels_init当成gt来计算损失呢，也就是最后一层fc的输出改成9，即网络预测9个类（包括0: 'unlabeled')，但不计算第0个类的损失(因为可以使用gather操作，将label=0的点剔除)，我想这样也可以训练的。
那么为什么要用valid_labels来计算呢？是想要减少参数量吗？

**Comment by QingyongHu** [comment]
Hi @LiDaiY, thanks for your interest in our work!

首先，直接在valid_labels_init上进行训练当然也是可以的，但是需要注意到在Semantic3D数据集中，label 0对应的是unclassified，在计算最终performance (mean IoU)时并不会考虑在label 0这一类。因此我们在训练网络的时候不计算这一类的loss，所以我们会将其remove掉再进行计算。

希望能够解答你的问题！

**Comment by LiDaiY** [comment]
> Hi @LiDaiY, thanks for your interest in our work!
> 
> 首先，直接在valid_labels_init上进行训练当然也是可以的，但是需要注意到在Semantic3D数据集中，label 0对应的是unclassified，在计算最终performance (mean IoU)时并不会考虑在label 0这一类。因此我们在训练网络的时候不计算这一类的loss，所以我们会将其remove掉再进行计算。
> 
> 希望能够解答你的问题！

谢谢！

**Comment by ginobilinie** [comment]
但实际应用过程中，没有0类是不行的。
