### ISSUE TITLE
how to visualize the semantic segmentation results on S3DIS dataset?

### ISSUE THREAD

**Issue by AnkyZhang** [QingyongHu/RandLA-Net#12]
HI @QingyongHu , thx for your released code. Could you please share your way to visualize  your results (e.g.: on S3DIS dataset) ? Because I found that the results ('test/Log_***********/Area_**********.ply' files) only have pred and label, without x, y, z,  and I have no idea how to make these .ply files visualized directly. Thanks in advance.

**Comment by QingyongHu** [comment]
Hi @AnkyZhang, All you need to do is read the corresponding original data with the same name. Please refer to [here ](https://github.com/QingyongHu/RandLA-Net/blob/04829e8bb57f802ff406a2f0aff4a5f64ef65179/utils/6_fold_cv.py#L21-L26) if you have no idea how to do it.

B.t.w, we use open3d to visualize the data, please refer to [this function](https://github.com/QingyongHu/RandLA-Net/blob/04829e8bb57f802ff406a2f0aff4a5f64ef65179/helper_tool.py#L286-L323) to see how to visualize the data. :)

**Comment by AnkyZhang** [comment]
@QingyongHu,  Thanks a lot !  It's very nice of you ! 👍

**Comment by Violetit** [comment]
> @QingyongHu, Thanks a lot! It's very nice of you! 👍

Hi @AnkyZhang, Have you successfully visualized the S3DIS dataset？ Could you please help me with this?  By the way, How about the visualization of semantic3d and semantickitti datasets?

**Comment by QingyongHu** [comment]
Both the results can be visualized by using open3d, please refer to[ this function](https://github.com/QingyongHu/RandLA-Net/blob/04829e8bb57f802ff406a2f0aff4a5f64ef65179/helper_tool.py#L286-L323) to see how to visualize the data. :)

**Comment by AnkyZhang** [comment]
Hi @Violetit ,  I'd glad to help you, but I haven't finished the model yet. Maybe we can discuss later.  BTW, I haven't tried on  semantic3d and semantickitti datasets.

**Comment by KangchengLiu** [comment]
I wonder how to save the prediction with x,y,z to .ply files that can be visualized directly (e.g.: on S3DIS dataset)?

**Comment by z393** [comment]
> > @QingyongHu, Thanks a lot! It's very nice of you! 👍
> 
> Hi @AnkyZhang, Have you successfully visualized the S3DIS dataset？ Could you please help me with this? By the way, How about the visualization of semantic3d and semantickitti datasets?

I have the same question. Did you solve it?

**Comment by youssef962** [comment]
@z393 same question, have you solved it?
