### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/data/semantic3d/original_ply

### ISSUE THREAD

**Issue by Esteban-25** [QingyongHu/RandLA-Net#13]
Hello! Thank you @QingyongHu for your work!
I am trying to prepare the semantic 3D dataset in my system (Ubuntu 18.04), but I get this error after running the "python utils/data_prepare_semantic3d.py" command:
"FileNotFoundError: [Errno 2] No such file or directory: '/data/semantic3d/original_ply"

Do you know what could be the problem?

**Comment by QingyongHu** [comment]
Hi @Esteban-25, thanks for your interest in our work!
Have you already download the Semantic3D dataset using the `download_semantic3d.sh` and put the data on this directory?

**Comment by Esteban-25** [comment]
Thanks for your reply. 
Yes, I have. The data is my project directory under ./data/semantic3d/original_data

**Comment by QingyongHu** [comment]
@Esteban-25 Please use terminal enter into your dataset directory, and use the command `pwd` to get your path, and then replace the path [here](https://github.com/QingyongHu/RandLA-Net/blob/04829e8bb57f802ff406a2f0aff4a5f64ef65179/utils/data_prepare_semantic3d.py#L15) with your custom path.
Hope this can solve your problem:)

**Comment by Esteban-25** [comment]
That helped! Thanks a lot :)

**Comment by ytyfeng** [comment]
I think it creates problems if you download data into `/data/semantic3d/...` since that is in the root directory and sometimes users on clusters don't have permission to write in it. I suggest that the first `/` be removed in the file path.
