### ISSUE TITLE
在使用自定义数据训练时，Iou计算出现NAN错误

### ISSUE THREAD

**Issue by YinBee** [QingyongHu/RandLA-Net#135]
您好，通过配置环境在S3DIS数据集训练时，运行您的代码可以正常运行。
但当我想使用自己的数据集训练，标注数据集是仿照着S3DIS的文件目录结构来进行的，在训练过程但是出现精度100%，IOU计算为nan值的错误，请问一下我这个问题出在哪呢？。第一个EPOCH的输出如下所示：

****EPOCH 0****
Step 00000050 L_out=1.121 Acc=0.99 ---  112.18 ms/batch
Step 00000100 L_out=0.471 Acc=1.00 ---  122.43 ms/batch
Step 00000150 L_out=0.284 Acc=1.00 ---  114.88 ms/batch
Step 00000200 L_out=0.196 Acc=1.00 ---  125.32 ms/batch
Step 00000250 L_out=0.187 Acc=1.00 ---  106.18 ms/batch
Step 00000300 L_out=0.150 Acc=1.00 ---  114.25 ms/batch
Step 00000350 L_out=0.077 Acc=1.00 ---  110.93 ms/batch
Step 00000400 L_out=0.073 Acc=1.00 ---  115.45 ms/batch
Step 00000450 L_out=0.068 Acc=1.00 ---  116.46 ms/batch
Step 00000500 L_out=0.057 Acc=1.00 ---  114.15 ms/batch
0 / 100
50 / 100
/Elements/RandLA-Net-plant/RandLANet.py:249: RuntimeWarning: invalid value encountered in true_divide
  iou = true_positive_classes[n] / float(gt_classes[n] + positive_classes[n] - true_positive_classes[n])
eval accuracy: 1.0
mean IOU:nan
Mean IoU = nan%
---------------------------------------
  nan | 100.00   nan   nan   nan   nan 
---------------------------------------

Best m_IoU is: 0.000

**Comment by VisionH222** [comment]
你好，请问你这个问题解决了吗，我在训练别的网络时同样遇到了指标为NaN的问题
