### ISSUE TITLE
No module named 'sklearn.neighbors._kd_tree'

### ISSUE THREAD

**Issue by chdjianfeng** [QingyongHu/RandLA-Net#14]
@QingyongHu  Hello! Thanks for your released code.  When I run python main_Semantic3D.py --mode train --gpu 0, an error oucured as below:

Load_pc_0: bildstein_station1_xyz_intensity_rgb
Traceback (most recent call last):
  File "main_Semantic3D.py", line 341, in <module>
    dataset = Semantic3D()
  File "main_Semantic3D.py", line 92, in __init__
    self.load_sub_sampled_clouds(cfg.sub_grid_size)
  File "main_Semantic3D.py", line 123, in load_sub_sampled_clouds
    search_tree = pickle.load(f)
ModuleNotFoundError: No module named 'sklearn.neighbors._kd_tree'

How can I solve it? Thank you!

**Comment by xiaowenwxw** [comment]
I have the same issue. 
Could you tell me how you solved this? Thank you!

**Comment by xiaowenwxw** [comment]
@chdjianfeng

**Comment by xiaoJ136** [comment]
> @chdjianfeng
I have the same issue.
Could you tell me how you solved this? Thank you!
@chdjianfeng

**Comment by xiaoJ136** [comment]
> @chdjianfeng

I load data which not be kdtree, and after loading data, KDTree(data).

**Comment by Qiyuan-Liu** [comment]
Hey buddy, have you solved the issue?

**Comment by biophase** [comment]
Had the same issue.

Solved it by deleting the .pkl files an regenerating them with:
```
python utils/data_prepare_s3dis.py
```

**Comment by ZHIBINJIAN** [comment]
根据提供的信息，问题似乎与您的代码中的序列化（pickling）和反序列化（unpickling）操作有关，这会导致一个模块未找到的错误。这与您之前提到的 sklearn.neighbors.kd_tree 无关。

可能的原因是，您在序列化数据时使用了 sklearn.neighbors.kd_tree，然后在反序列化时出现了问题。这可能是因为您序列化了一个具有特定版本 scikit-learn 的 KDTree 对象，但在反序列化时运行的环境中缺少相同版本的 scikit-learn，或者是因为序列化的对象与 scikit-learn 版本不兼容。

要解决这个问题，您可以考虑以下几个步骤：

检查 scikit-learn 版本：确保您的代码和运行环境中都使用了相同版本的 scikit-learn。您可以使用 pip show scikit-learn 来查看已安装的 scikit-learn 版本，并确保它与您序列化数据时使用的版本匹配。

重新序列化数据：如果您在不同的环境中运行代码，可以尝试重新生成或重新序列化数据，以确保使用的 scikit-learn 版本匹配。

在环境中安装 scikit-learn：确保在您的运行环境中安装了 scikit-learn。您可以使用 pip install scikit-learn 来安装它，确保版本与您的代码兼容。

检查模块名称：确保您的代码中没有导入错误，包括大小写和模块名称的正确性。正确的导入应该是 from sklearn.neighbors import KDTree。

如果您尝试了这些步骤仍然无法解决问题，那么可能需要更多关于您的代码和环境的信息来提供更具体的建议。
我是检查版本解决的。懒得翻译了，你们参考下
