### ISSUE TITLE
about build nearest_neighbors in windows

### ISSUE THREAD

**Issue by huixiancheng** [QingyongHu/RandLA-Net#166]
Hi. I have try to bulid nearest_neighbors in windows. 
The result like this.
![QQ截图20210701102747](https://user-images.githubusercontent.com/65054204/124055740-083a9900-da57-11eb-9a8e-f994eaea8915.png)
Look like it's a pyd file. How to import it? 
![QQ截图20210701102802](https://user-images.githubusercontent.com/65054204/124055824-2e603900-da57-11eb-9dd4-d1bd2b59d2f6.png)
Or just I make some mistakes in somewhere.
Thank for any help may be able to provide

**Comment by huixiancheng** [comment]
maybe solved it.

**Comment by SuperKX** [comment]
hi @huixiancheng , I encounter the same issue in Windows.  could you please give me some suggests, thanks a lot.

**Comment by huixiancheng** [comment]
rename the .pyd to this may lead to success. 
![QQ截图20210830193752](https://user-images.githubusercontent.com/65054204/131333428-bb14a68a-4cfd-4f3b-8e52-b2dffcf67071.png)
Moreover, you may be follow this. https://github.com/QingyongHu/RandLA-Net/issues/73#issue-622406229
In fact, even you have build nearest_neighbors successfully in windows,  there are also have some small mistakes. So I think the best way is use a Ubuntu system.

**Comment by SuperKX** [comment]
@huixiancheng thanks a lot, i'll try in ubuntu

**Comment by youssef962** [comment]
@huixiancheng 
I try to build nearest_neighbors on windows as I don't have the pyd file but it shows me this error:
`running install
running build
running build_ext
skipping 'knn.cpp' Cython extension (up-to-date)
building 'nearest_neighbors' extension
error: Unable to find vcvarsall.bat
`
how did you solve it?
