### ISSUE TITLE
problem with compile_op.sh

### ISSUE THREAD

**Issue by youssef962** [QingyongHu/RandLA-Net#171]
when I run the shell script file it keeps saying :
```
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from Cython.Distutils import build_ext
ImportError: No module named Cython.Distutils
```
I installed cython but  no change, any help?!

**Comment by ssteele-kraken** [comment]
Did you ever find a solution for this?

**Comment by youssef962** [comment]
@ssteele-kraken
Yes i installed multiple versions of python so it was installed on one and not the other and i was running the code on the 2nd one. So make sure you install cython on the version you are using to run the code
