### ISSUE TITLE
How do i visualize predicted data?

### ISSUE THREAD

**Issue by IMSHJI** [QingyongHu/RandLA-Net#172]
I trained through 'sh jobs_6_fold_cv_s3dis.sh'.
I also checked the mIoU through 'python utils/6_fold_cv.py'.

The ply files created in the test folder are in binary format and cannot be visualized. (in Meshlab)
I tried to visualize it through --mode vis of main_S3DIS.py, but it is assumed that existing files were utilized. 
(python -B main_S3DIS.py --gpu 0 --mode vis --test_area 1)

How do I visualize predicted data?

**Comment by IMSHJI** [comment]
I've checked the following code, but it didn't take advantage of it...

    @staticmethod
    def draw_pc_sem_ins(pc_xyz, pc_sem_ins, fix_color_num=None):
        if fix_color_num is not None:
            ins_colors = Plot.random_colors(fix_color_num + 1, seed=2)
        else:
            ins_colors = Plot.random_colors(len(np.unique(pc_sem_ins)) + 1, seed=2)  # cls 14

        ##############################
        sem_ins_labels = np.unique(pc_sem_ins)
        sem_ins_bbox = []
        Y_colors = np.zeros((pc_sem_ins.shape[0], 3))
        for id, semins in enumerate(sem_ins_labels):
            valid_ind = np.argwhere(pc_sem_ins == semins)[:, 0]
            if semins <= -1:
                tp = [0, 0, 0]
            else:
                if fix_color_num is not None:
                    tp = ins_colors[semins]
                else:
                    tp = ins_colors[id]

            Y_colors[valid_ind] = tp

            ### bbox
            valid_xyz = pc_xyz[valid_ind]

            xmin = np.min(valid_xyz[:, 0]);
            xmax = np.max(valid_xyz[:, 0])
            ymin = np.min(valid_xyz[:, 1]);
            ymax = np.max(valid_xyz[:, 1])
            zmin = np.min(valid_xyz[:, 2]);
            zmax = np.max(valid_xyz[:, 2])
            sem_ins_bbox.append(
                [[xmin, ymin, zmin], [xmax, ymax, zmax], [min(tp[0], 1.), min(tp[1], 1.), min(tp[2], 1.)]])

        Y_semins = np.concatenate([pc_xyz[:, 0:3], Y_colors], axis=-1)
        Plot.draw_pc(Y_semins)
        return Y_semins

**Comment by IMSHJI** [comment]
I succeeded in visualization!

Because it is a binary file format, it was difficult to read the data in text format, but it was successfully visualized by combining the x, y, z data of the original data and the predicted label data. (Plot.draw_pc_sem_ins())
Is there any other reason to save the file in binary format..?

It is a disgraceful word, but can you recommend which lectures are recommended for non-majors to learn the related deep learning code..?
I still think that I am a novice when it comes to code, but I want to improve my skills through code..!

Thanks for your code contribution.

**Comment by youssef962** [comment]
How did you visualized it?
state what you have  done please

**Comment by youssef962** [comment]
@IMSHJI how did you combined the original file with the output predicted ply file?
