### ISSUE TITLE
Error while running main_Semantic3d.py

### ISSUE THREAD

**Issue by KiranAkadas** [QingyongHu/RandLA-Net#21]
Hello,
I'm using my own data for training the model and have prepared as per the instructions with the same environment as mentioned in the documentation.
But, when I run the training file - main_Semantic3d.py, just before the 1st epoch begins, I get the error for the line
_queried_pt_weight = np.array([self.class_weight[split][0][n] for n in queried_pc_labels])_ 
with the msg - too many array indices.
I tried fixing it but did not understand why is there a loop inside. In self.class_weights, we have an array for each of the 3 splits with only one integer. Please help me out.

**Comment by QingyongHu** [comment]
Hi @KiranAkadas. Thanks for your interest.

For your custom dataset, the queried_pt_weight is not necessary, I would suggest you ignore this and just replace it as:

`queried_pt_weight = 1
`

we are using this mainly to mitigate the problem of imbalanced distribution in Semantic3D dataset. Therefore, we aim to sample the point from the minority categories as much as possible, _self.class_weights_  is defined based on the proportion of each semantic categories, and used to adjust the probability of a point belonging to a specific category being selected.

Hope this would be helpful!

**Comment by KiranAkadas** [comment]
Thankyou very much for the speedy resolution.
It fixed my problem.
