### ISSUE TITLE
AttributeError: module 'utils.nearest_neighbors' has no attribute 'knn_batch'

### ISSUE THREAD

**Issue by Jaychouxq** [QingyongHu/RandLA-Net#218]
after successfully build nearest_neighbors
`running build_ext
cythoning knn.pyx to knn.cpp
building 'nearest_neighbors' extension
creating build
creating build\temp.win-amd64-3.7
creating build\temp.win-amd64-3.7\Release
"E:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -I./ -IC:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\numpy\core\include 
-IC:\ProgramData\Anaconda3\envs\tensorflow\include -IC:\ProgramData\Anaconda3\envs\tensorflow\Include "-IE:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Window
s Kits\NETFXSDK\4.8\include\um" "-IE:\Windows Kits\10\include\10.0.19041.0\ucrt" "-IE:\Windows Kits\10\include\10.0.19041.0\shared" "-IE:\Windows Kits\10\include\10.0.19041.0\um" "-IE:\Windows Kits\10\include\10.0.19041.0\winrt" "-IE:\
Windows Kits\10\include\10.0.19041.0\cppwinrt" "-IE:\Windows Kits\10\Include\10.0.18362.0\ucrt" "-IE:\Windows Kits\10\Include\10.0.18362.0\um" "-IE:\Windows Kits\10\Include\10.0.18362.0\shared" "-IE:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" /EHsc /Tpknn.cpp /Fobuild\temp.win-amd64-3.7\Release\knn.obj -std=c++11 -fopenmp
cl: 命令行 warning D9002 :忽略未知选项“-std=c++11”
cl: 命令行 warning D9002 :忽略未知选项“-fopenmp”
knn.cpp
C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
"E:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -I./ -IC:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\numpy\core\include 
-IC:\ProgramData\Anaconda3\envs\tensorflow\include -IC:\ProgramData\Anaconda3\envs\tensorflow\Include "-IE:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Window
s Kits\NETFXSDK\4.8\include\um" "-IE:\Windows Kits\10\include\10.0.19041.0\ucrt" "-IE:\Windows Kits\10\include\10.0.19041.0\shared" "-IE:\Windows Kits\10\include\10.0.19041.0\um" "-IE:\Windows Kits\10\include\10.0.19041.0\winrt" "-IE:\
Windows Kits\10\include\10.0.19041.0\cppwinrt" "-IE:\Windows Kits\10\Include\10.0.18362.0\ucrt" "-IE:\Windows Kits\10\Include\10.0.18362.0\um" "-IE:\Windows Kits\10\Include\10.0.18362.0\shared" "-IE:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" /EHsc /Tpknn_.cxx /Fobuild\temp.win-amd64-3.7\Release\knn_.obj -std=c++11 -fopenmp
cl: 命令行 warning D9002 :忽略未知选项“-std=c++11”
cl: 命令行 warning D9002 :忽略未知选项“-fopenmp”
knn_.cxx
knn_.cxx(143): warning C4244: “参数”: 从“time_t”转换到“unsigned int”，可能丢失数据
knn_.cxx(210): warning C4244: “参数”: 从“time_t”转换到“unsigned int”，可能丢失数据
"E:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\ProgramData\Anaconda3\envs\tensorfl
ow\libs /LIBPATH:C:\ProgramData\Anaconda3\envs\tensorflow /LIBPATH:C:\ProgramData\Anaconda3\envs\tensorflow\PCbuild\amd64 "/LIBPATH:E:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\lib\x64" "/LIB
PATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:E:\Windows Kits\10\lib\10.0.19041.0\ucrt\x64" "/LIBPATH:E:\Windows Kits\10\lib\10.0.19041.0\um\x64" "/LIBPATH:E:\Windows Kits\10\Lib\10.0.18362.0\um\x64" "/LIB
PATH:E:\Windows Kits\10\Lib\10.0.18362.0\ucrt\x64" "/LIBPATH:E:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\lib\x64" /EXPORT:PyInit_nearest_neighbors build\temp.win-amd64-3.7\Release\knn.obj build\temp.win-amd64-3.7\Release\knn_.obj /OUT:E:\夏琪\tensorflow\RandLA-Net-master\utils\nearest_neighbors\nearest_neighbors.pyd /IMPLIB:build\temp.win-amd64-3.7\Release\nearest_neighbors.lib -std=c++11 -fopenmp
LINK : warning LNK4044: 无法识别的选项“/std=c++11”；已忽略
LINK : warning LNK4044: 无法识别的选项“/fopenmp”；已忽略
  正在创建库 build\temp.win-amd64-3.7\Release\nearest_neighbors.lib 和对象 build\temp.win-amd64-3.7\Release\nearest_neighbors.exp
正在生成代码
已完成代码的生成
`
there is still an error
`AttributeError: module 'utils.nearest_neighbors' has no attribute 'knn_batch'`

**Comment by xiangbiyedexiaoliu** [comment]
Hello, I also met the same problem, may I ask if you have a solution.
你好，我也遇到了同样的问题，请问你已经有解决办法了么。

**Comment by zhao2287491659** [comment]
你好，我也遇到了同样的问题，请问您解决了吗

**Comment by Xavier-wa** [comment]
same question,any solution

**Comment by zousdf** [comment]
你好，我也遇到同样的问题，请问怎么解决的？
