### ISSUE TITLE
Cannot found module named 'nearest_neighbors.nearest_neighbors'

### ISSUE THREAD

**Issue by zhaoqiong12** [QingyongHu/RandLA-Net#222]
When I want to recurrent this net code ,this issue  has not been resolved.Unlike the paper ,I am using Windows (10) system,all module have been prepared,but this problem in the help_tools.py  has been there.
![image](https://user-images.githubusercontent.com/96518958/171004965-e4c6503e-e697-4f30-890d-631019338718.png)

**Comment by renqi1998** [comment]
这个问题好像是你的python版本太高了，你可以试着降到3.6，我之前用3.8的也是报错，但是将版本降到3.6，就能编译成功，并且显示有这个模块
