### ISSUE TITLE
quantitative results

### ISSUE THREAD

**Issue by ayoubOUSSM2021** [QingyongHu/RandLA-Net#223]
Hello ; 
I would like to know how you obtained the quantitative results mentioned in the table below, are these the same results you obtained at the end of the training or did you use the test data to calculate these metrics, but the test data does not contain the labels.
Sincerely 

![687474703a2f2f72616e646c612d6e65742e63732e6f782e61632e756b2f696d67732f53656d616e74696333445f7461626c652e706e67](https://user-images.githubusercontent.com/87376316/172817331-56fcaace-f670-47e4-bd29-6f8005bbdeff.png)

**Comment by QingyongHu** [comment]
Thanks for your interest in our work!

This result is borrowed from the benchmark website. Please refer to [here](http://www.semantic3d.net/view_results.php?chl=2).

I hope this could answer your question.

This issue is about to close, please reopen if necessary
