### ISSUE TITLE
关于DP.shuffle_idx

### ISSUE THREAD

**Issue by TangVVV** [QingyongHu/RandLA-Net#228]
您好，请问为什么通过kdtree找到临近点后，要使用shuffle_idx将这些点洗牌呢，这样的话，取到的点云块会不会形状就不同了，比如取到的点云块是一辆小汽车，打乱后就看不出来是一辆小汽车了。不太理解DP.shuffle_idx的作用，可否不吝赐教

**Comment by zero406-CC** [comment]
打乱的原因不清楚，但是这个打乱的是id点的下标，又不是打乱点云空间位置，点云本来都是无序的，即使换顺序他空间坐标又没换

**Comment by TangVVV** [comment]
> 打乱的原因不清楚，但是这个打乱的是id点的下标，又不是打乱点云空间位置，点云本来都是无序的，即使换顺序他空间坐标又没换

哦哦理解了，是我想错了，谢谢。不过打乱原因确实还是不太理解

**Comment by QingyongHu** [comment]
不好意思才回复，感谢对我们工作的关注！

如 @zero406-CC 所述，打乱的只是下标，并不会改变空间的几何结构。至于打乱的原因，主要是考虑在训练过程中增加多样性，可以理解为一种形式的data augmentation，否则每次以某个点为中心找到的subcloud都是完全相同的，有overfit的风险。
