### ISSUE TITLE
Train SensatUrban

### ISSUE THREAD

**Issue by xsf777** [QingyongHu/RandLA-Net#229]
I find it on SensatUrban(https://github.com/QingyongHu/SensatUrban),he tell RandLA-Net can train  SensatUrban.
![image](https://user-images.githubusercontent.com/89497789/178431979-39ff8c4e-8529-4265-9e29-910b245d8070.png)
![image](https://user-images.githubusercontent.com/89497789/178432348-e8b992f3-97c3-4e7d-ae7a-5bd944a6befb.png)
but I don't find main_SensatUrban.py.

**Comment by QingyongHu** [comment]
Thanks for your interest in our work!

Sorry for the confusion, the `main_SensatUrban.py` could be found in this [repo](https://github.com/QingyongHu/SensatUrban).

I hope this answers your question.

**Comment by QingyongHu** [comment]
This issue is about to close, please reopen this issue if necessary~
