### ISSUE TITLE
question about get_batch_gen() in main_SemanticKITTI.py

### ISSUE THREAD

**Issue by amiltonwong** [QingyongHu/RandLA-Net#23]
Hi, @QingyongHu ,

I found that a multiple of 4 is applied in [get_batch_gen()](https://github.com/QingyongHu/RandLA-Net/blob/master/main_SemanticKITTI.py#L63) of main_SemanticKITTI.py. Could you answer the reason and what is the positive effect about this multiple (4)? 

THX!

**Comment by QingyongHu** [comment]
Hi, @amiltonwong the main idea is to make sure that every point could be evaluated.

**Comment by amiltonwong** [comment]
Thanks @QingyongHu . OK, that means it's a heuristic value.
