### ISSUE TITLE
Visualization of semanticKITTI

### ISSUE THREAD

**Issue by GUDKS** [QingyongHu/RandLA-Net#25]
After running the test program on the semanticKITTI dataset, I got some .label files, but the number of points in the label file  is different from the original point cloud file. I want to know how to use these label files to visualize the point cloud in the test sequences? 
Looking forward to your reply

**Comment by QingyongHu** [comment]
Hi @GUDKS, thanks for your interest in our work!
The number of points should be the same if you follow our instructions step by step. For visualization, we suggest you use this [function](https://github.com/QingyongHu/RandLA-Net/blob/195d27fde412e99ae3ee70bd1529a3debc904781/helper_tool.py#L287-L323).

**Comment by longmalongma** [comment]
> After running the test program on the semanticKITTI dataset, I got some .label files, but the number of points in the label file is different from the original point cloud file. I want to know how to use these label files to visualize the point cloud in the test sequences?
> Looking forward to your reply

hello,I have same problem,have you solved this problem?
