### ISSUE TITLE
custom training data don't contain all the labels.

### ISSUE THREAD

**Issue by CiroLewis66** [QingyongHu/RandLA-Net#252]
For example, I have a dataset that contains three types:( unlabeled points, ground points, and off-ground points) but one of the data in the dataset only contains two types(ground points, and off-ground points), which will cause errors during training(self.class_weights).

**Comment by QingyongHu** [comment]
Hi @CiroLewis66 

Thank you for your interest in our work, and for taking the time to bring this issue to our attention. 

Regarding the issue you raised, I would say the simplest solution is to manually add an unlabeled point to the singular data. This will help ensure that the code works correctly, and it should not have any visible impact on the results.
