### ISSUE TITLE
问题：如何只提取感兴趣的点？

### ISSUE THREAD

**Issue by HlKun** [QingyongHu/RandLA-Net#258]
胡博士，您好
       关于点云分割，我有一个问题，就是如何从点云中只提取我感兴趣的对象；
      如果我的点云中有车辆、道路、建筑等其他对象，但是我只想分割出点云中的车辆，为车辆赋予一个独特的颜色，其他对象都赋予白色；我是否可以使用只包含车辆的点云数据来进行模型训练；这样训练出来的模型能否在任意场景中识别到车辆？
      还是需要为场景中的所有对象都赋予一个标签来进行训练？
      面对这种情况我应该如何准备训练数据？

**Comment by QingyongHu** [comment]
@HlKun 
你好，感谢对我们工作的关注！

对于这种情况，我建议将其视作一个二分类的问题，比如说将所有的车辆标签值赋为1，其余所有其他的类别赋值为0，然后去训练网络即可。需要注意的是，这种情况下由于属于车辆的点数会远远小于其他背景的点数，所以建议可能采取focal loss或者weight cross entropy等损失函数来解决一下类别不平衡的问题
