### ISSUE TITLE
No such file or directory:'/data/S3DIS/original_ply Error

### ISSUE THREAD

**Issue by WuDaoJiuXiao** [QingyongHu/RandLA-Net#259]
when I run command "python utils/data_prepare_s3dis.py"，have the error happend "No such file or directory:'/data/S3DIS/original_ply'",The dataset has been downloaded and unzipped to the / data/S3DIS directory as readmd said，So is it because there are still datasets that haven't been downloaded?

**Comment by QingyongHu** [comment]
@WuDaoJiuXiao 
Thank you for your interest in my work. Regarding the dataset path, it is possible that there might be an error in the path you are using. My suggestion would be to add a breakpoint or print command in your code to confirm whether the path points to the correct directory. This could help you identify the root of the issue and resolve it more efficiently.

If this suggestion does not solve the issue or if you have any further questions, please do not hesitate to reach out to me. I would be happy to assist you in any way that I can.

Qingyong
