### ISSUE TITLE
关于代码运行问题

### ISSUE THREAD

**Issue by jiang4869** [QingyongHu/RandLA-Net#26]
请问一下，运行compile_op.sh这个进行编译的时候对gcc,g++版本有特别要求吗。我在编译成果中代码出现了warning。之后运行jobs_6_fold_cv_s3dis.sh的时候出现了参数错误提示。

**Comment by QingyongHu** [comment]
Hello，我们在gcc 5.4.0环境下运行代码没有问题，编译有warning很正常，不知道你说的参数错误提示具体是什么？

**Comment by jiang4869** [comment]
bug已经解决了，是因为读取路径'/data/S3DIS'出问题了导致数据没被读入才出现参数错误，感谢回答

**Comment by jiang4869** [comment]
> 您好，我们在gcc 5.4.0环境下运行代码没有问题，编译有警告很正常，不知道你说的参数错误提示具体是什么？

bug已经解决了，是因为读取路径'/data/S3DIS'出问题了导致数据没被读入才出现参数错误，感谢回答

**Comment by forever-LYQ** [comment]
请问 都是需要哪些地方的 data修改 我改了很多地方还是没有运行成功，非常希望您能答复
