### ISSUE TITLE
关于数据scale问题

### ISSUE THREAD

**Issue by pomelo93** [QingyongHu/RandLA-Net#27]
您好，我想请问一下 ，该算法能处理点云数据的最大量级是多少呢？是10^6吗？实际中，我的点云数据量有上亿，训练之前我是否应该把数据抽稀成百万级别的？期待您的回答！感谢～

**Comment by QingyongHu** [comment]
你好，欢迎对我们工作的关注！
在单块RTX2080Ti上面是差不多一百万个点左右，建议参考下Semantic3D部分的代码，因为Semantic3D数据集共有40亿点，单个点云最大也有几亿个点。

希望对你有帮助！

**Comment by jingyibo123** [comment]
胡博你好 @QingyongHu  请问上面提到

> 在单块RTX2080Ti上面是差不多一百万个点左右

是指训练的时候实际送进网络的点数量吗？

我将SemanticKITTI每帧处理成大约一百万点左右，在1080Ti（11GB）显存用下面的配置仍然会OOM，
`   

    k_n = 16  # KNN
    num_layers = 4  # Number of layers
    num_points = 4096 * 200  # Number of input points
    num_classes = 19  # Number of valid classes
    sub_grid_size = 0.06  # preprocess_parameter

    batch_size = 1  # batch_size during training
    val_batch_size = 1  # batch_size during validation and test
    train_steps = 500  # Number of steps per epochs
    val_steps = 100  # Number of validation steps per epoch

    sub_sampling_ratio = [4, 4, 4, 4]  # sampling ratio of random sampling at each layer
    d_out = [16, 64, 128, 256]  # feature dimension
    num_sub_points = [num_points // 4, num_points // 16, num_points // 64, num_points // 256]`

多谢解答

**Comment by QingyongHu** [comment]
Hi @jingyibo123 
首先，我们指的是inference，也就是训练好的模型能够处理大约一百万点左右，不是训练的时候。因为训练的时候需要back propogation和计算梯度等，所有会占用的显存多很多，建议你train好模型以后试一下inference。

**Comment by hanm2019** [comment]
> 胡博你好 @QingyongHu 请问上面提到
> 
> > 在单块RTX2080Ti上面是差不多一百万个点左右
> 
> 是指训练的时候实际送进网络的点数量吗？
> 
> 我将SemanticKITTI每帧处理成大约一百万点左右，在1080Ti（11GB）显存用下面的配置仍然会OOM， `
> 
> ```
> k_n = 16  # KNN
> num_layers = 4  # Number of layers
> num_points = 4096 * 200  # Number of input points
> num_classes = 19  # Number of valid classes
> sub_grid_size = 0.06  # preprocess_parameter
> 
> batch_size = 1  # batch_size during training
> val_batch_size = 1  # batch_size during validation and test
> train_steps = 500  # Number of steps per epochs
> val_steps = 100  # Number of validation steps per epoch
> 
> sub_sampling_ratio = [4, 4, 4, 4]  # sampling ratio of random sampling at each layer
> d_out = [16, 64, 128, 256]  # feature dimension
> num_sub_points = [num_points // 4, num_points // 16, num_points // 64, num_points // 256]`
> ```
> 
> 多谢解答

请问SemanticKITTI数据集如何处理成每帧百万规模的点的呢？我统计了一下SemanticKITTI每个文件，平均有120000个点，也就是十万这个量级，如何处理成百万的呢？

**Comment by QingyongHu** [comment]
@hanm2019 请参照上面的回复，我们指的是inference，也就是训练好的模型能够处理大约一百万点左右，不是训练的时候。因为训练的时候需要back propogation和计算梯度等，所有会占用的显存多很多，建议你train好模型以后试一下inference。

**Comment by hanm2019** [comment]
嗯嗯，我理解是inference的过程，但不清楚如何用SemanticKITTI数据集构建每帧百万规模的点云

**Comment by jingyibo123** [comment]
> > 胡博你好 @QingyongHu 请问上面提到
> > > 在单块RTX2080Ti上面是差不多一百万个点左右
> > 
> > 
> > 是指训练的时候实际送进网络的点数量吗？
> > 我将SemanticKITTI每帧处理成大约一百万点左右，在1080Ti（11GB）显存用下面的配置仍然会OOM， `
> > ```
> > k_n = 16  # KNN
> > num_layers = 4  # Number of layers
> > num_points = 4096 * 200  # Number of input points
> > num_classes = 19  # Number of valid classes
> > sub_grid_size = 0.06  # preprocess_parameter
> > 
> > batch_size = 1  # batch_size during training
> > val_batch_size = 1  # batch_size during validation and test
> > train_steps = 500  # Number of steps per epochs
> > val_steps = 100  # Number of validation steps per epoch
> > 
> > sub_sampling_ratio = [4, 4, 4, 4]  # sampling ratio of random sampling at each layer
> > d_out = [16, 64, 128, 256]  # feature dimension
> > num_sub_points = [num_points // 4, num_points // 16, num_points // 64, num_points // 256]`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 多谢解答
> 
> 请问SemanticKITTI数据集如何处理成每帧百万规模的点的呢？我统计了一下SemanticKITTI每个文件，平均有120000个点，也就是十万这个量级，如何处理成百万的呢？

利用odometry的信息将多个文件同一坐标系下空间累积就可以获得稠密的语义点云。

**Comment by jingyibo123** [comment]
> 嗯嗯，我理解是inference的过程，但不清楚如何用SemanticKITTI数据集构建每帧百万规模的点云

利用odometry的信息将多个文件同一坐标系下空间累积就可以获得稠密的语义点云。

每帧的点云数量还是保持不变的。
