### ISSUE TITLE
GPU memory RTX3090

### ISSUE THREAD

**Issue by Sylva-Lin** [QingyongHu/RandLA-Net#277]
The same batchsize = 6 and N = 4096*11, why does the GPU occupy 23G, the author can run in 2080Ti, but the GPU ceiling of 2080Ti is 12G, why is my occupation so high, in the same configuration

**Comment by Sylva-Lin** [comment]
And when I modify batchsize and N, there is no effect on the GPU occupation, the environment I use says Tf2.6, is it caused by environmental reasons?

**Comment by Sylva-Lin** [comment]
solve

**Comment by zcustc-10** [comment]
hello, how do you solve this problem? I meet the same situation. Thank you
