### ISSUE TITLE
About testing question

### ISSUE THREAD

**Issue by pomelo93** [QingyongHu/RandLA-Net#28]
您好，关于测试的脚本有点疑惑。tester_S3DIS.py  57行，测试的时候用到了dataset.val_labels，但是在实际的测试中，我是不知道每个point的label，那么我测试的时候val_label该怎么初始化？期待您的回复！感谢～

**Comment by QingyongHu** [comment]
因为S3DIS本身又test set的label, 所以我们用这个方便评估结果。对于没有label的情况，建议直接参考Semantic3D部分的测试代码。
