### ISSUE TITLE
Semantic KITTI error: from open3d import linux as open3d

### ISSUE THREAD

**Issue by aljosaosep** [QingyongHu/RandLA-Net#29]
Hi, 

When following the instructions for inference/training on Semantic KITTI, I got an error running data_prepare_semantickitti.py (error importing from open3d import linux as open3d). I followed the instructions step-by-step.

Fix: I've upgraded Open3D from 0.8 (recommended) to 0.9 (latest): pip install open3d==0.9

**Comment by CoolLoveBoy** [comment]
Hello! I have the same question, and I also install open3d==0.9. However it has the same error that cannot import name linux from open3d. Could you tell what can I do it ?

**Comment by bhaskar-anand-iith** [comment]
I am still getting this error. If anybody solved it?
