### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by lxtGH** [QingyongHu/RandLA-Net#32]
Hi! Thanks for your opensourced code. 
I am new to this field. 
I wonder the training time of RandLANet on these three large scale datasets. It seems you only use one GPU for training.  So how long it costs to achieves the paper results?

**Comment by QingyongHu** [comment]
Hi @lxtGH, thanks for your interest in our work!

Yes, we only use a single GPU during training. It approximately takes about 3-4 days (one day for each dataset) to get the result in our paper on the RTX 2080TI GPU with AMD 3700X CPU.

**Comment by lxtGH** [comment]
@QingyongHu ,Thanks for your reply. So I wonder why not use multiple GPU to speed up the training ??

**Comment by QingyongHu** [comment]
I would be very happy if you could give me more computing resources 😀
