### ISSUE TITLE
motorcyclist label

### ISSUE THREAD

**Issue by davidlmljll** [QingyongHu/RandLA-Net#33]
Hello. Firstly，thank you for your work. When I was training SemanticKITTI, I noticed that the mini target motorcyclist tag was always 0 (max epoch 100), and I noticed that the label in your article was 4.6% and on github it was 7.2%. Did you modify the training parameters or use some data enhancement techniques?
Thank you for any help!

**Comment by QingyongHu** [comment]
Hi, @davidlmljll, thanks for your interest in our work!
All of our results are based on the code provided, you are also encouraged to download the model we provided in Google drive.
For the minor modifications, please refer to this issue for detail  #19

**Comment by HenryJunW** [comment]
@davidlmljll  Same problem, did you solve it?
