### ISSUE TITLE
dataset.min_possibility 

### ISSUE THREAD

**Issue by kylincar** [QingyongHu/RandLA-Net#34]
@QingyongHu  Hi,  I have two quesions about your work.

1. What does min_possibility mean at testing phase for semantickitti?

2. I follow your step to install the dependce and use your pretrained model for semantickitti testing, but the number of points in the label file is different from the original point cloud file.  so the visualization function throw error like:
```
Traceback (most recent call last):
  File "kitti_visualization.py", line 23, in <module>
    Plot.draw_pc_sem_ins(points , labels)
  File "/projects/RandLA-Net\helper_tool.py", line 310, in draw_pc_sem_ins
    valid_xyz = pc_xyz[valid_ind]
IndexError: index 89267 is out of bounds for axis 0 with size 87936
```
Why the number is different ?

Waiting for your reply. Thank you.

**Comment by QingyongHu** [comment]
Hi @kylincar, thanks for your interest in our work!

For question 1, please refer to this issue #11 

For question 2, can you please check if you have done this step?

`python utils/data_prepare_semantickitti.py
`

Many thanks!
