### ISSUE TITLE
InternalError (see above for traceback): Blas xGEMM launch failed 

### ISSUE THREAD

**Issue by longmalongma** [QingyongHu/RandLA-Net#36]
Hi,thanks for your great work!when i want to train your model,i meet this problem,can you help me ?looking forward to your reply.
InternalError (see above for traceback): Blas xGEMM launch failed : a.shape=[1,1024,3], b.shape=[1,3,2048], m=1024, n=2048, k=3
	 [[Node: tower_1/layer1/MatMul = BatchMatMul[T=DT_FLOAT, adj_x=false, adj_y=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](tower_1/layer1/ExpandDims_1, tower_1/layer1/transpose)]]
	 [[Node: tower_1/fa_layer3/conv_0/bn/cond/add_1/_1179 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3471_tower_1/fa_layer3/conv_0/bn/cond/add_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by QingyongHu** [comment]
Hi @longmalongma. Unfortunately, I can't give you an exact solution based on this information. Where did you meet this problem?

**Comment by longmalongma** [comment]
> Hi @longmalongma. Unfortunately, I can't give you an exact solution based on this information. Where did you meet this problem?

Thanks for your reply,when I run main_SemanticKITTI.py,I think it's my environmental problems. Oddly enough, my environment is fine, but that's what happens when you train some models.

**Comment by QingyongHu** [comment]
What is the meaning of some models? Can you be more specific and put all the error messages? I don't understand what is the meaning of these variables...

_a.shape=[1,1024,3], b.shape=[1,3,2048], m=1024, n=2048, k=3_

**Comment by longmalongma** [comment]
> What is the meaning of some models? Can you be more specific and put all the error messages? I don't understand what is the meaning of these variables...
> 
> _a.shape=[1,1024,3], b.shape=[1,3,2048], m=1024, n=2048, k=3_


Sorry, I didn't make it clear that I also encountered the same problem when training the DGCNN model. I will try to solve this problem by creating a new deep learning environment.　Here is all the error information: 

InternalError (see above for traceback): Blas xGEMM launch failed : a.shape=[1,1024,3], b.shape=[1,3,4096], m=1024, n=4096, k=3
	 [[Node: tower_0/layer1/MatMul = BatchMatMul[T=DT_FLOAT, adj_x=false, adj_y=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](tower_0/layer1/ExpandDims_1, tower_0/layer1/transpose)]]
	 [[Node: tower_0/gradients/AddN_14/_1699 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_5123_tower_0/gradients/AddN_14", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
