### ISSUE TITLE
mean accuracy

### ISSUE THREAD

**Issue by juzi-dj** [QingyongHu/RandLA-Net#39]
Hello, I am honored to read your paper and have benefited a lot from it. However, I have a question at present, I can't find the code where to output the mAcc of dataset, such as S3DIS. This may be a very simple question, but I sincerely hope to get your answer, thank you!

**Comment by QingyongHu** [comment]
Hi @juzi-dj, thanks for your interest in our work!
Sorry for missing this part of code, please check [here](https://github.com/QingyongHu/RandLA-Net/blob/56f6c2f92f75306bbc7ff23da84b05eb8c0ed7ee/utils/6_fold_cv.py#L49-L54) for the latest code.
Many thanks :handshake:

**Comment by juzi-dj** [comment]
Thank you for your reply  @QingyongHu
