### ISSUE TITLE
dilation rate schedule

### ISSUE THREAD

**Issue by linhaojia13** [QingyongHu/RandLA-Net#42]
Thank you for your good works! Could you tell me the dilation rate applied in each layer on the S3DIS segmentation?

**Comment by QingyongHu** [comment]
Hi @linhaojia13 , thanks for your interest in our work!

Although we have a dilated residual block in our RandLA-Net, but it is not exactly the "dilated convolution" in 2D CNN network. In fact, we find the same number of neighboring points (k=16) through KNN in each layer,  but we stack two LocSE and attentive pooling together in each residual block. This is also able to increase the receptive field of the network, so we called it a dilated residual block.

**Comment by linhaojia13** [comment]
Thank you for your patient reply. Have a nice day!
