### ISSUE TITLE
SemanticKITTI数据集

### ISSUE THREAD

**Issue by pomelo93** [QingyongHu/RandLA-Net#44]
您好，方便提供 SemanticKITTI数据集百度网盘下载链接吗？感谢！

**Comment by QingyongHu** [comment]
Hi @pomelo93, 感谢对我们工作的关注！
非常抱歉我们并没有百度网盘的链接，而且从英国访问百度网盘速度也很慢...

**Comment by honggesmile** [comment]
> 您好，方便提供 SemanticKITTI数据集百度网盘下载链接吗？感谢！

您好，能加个微信沟通下吗，数据集我有办法下载到。我微信：vision2d

**Comment by zsy-hub** [comment]
我有下载好的 我也在调这个网络 可以微信交流一下吗 我微信Zsy1103216882

**Comment by jasonwjw** [comment]
> 

你好，能提供一下SemanticKITTI的百度云链接吗
