### ISSUE TITLE
Visualization problems

### ISSUE THREAD

**Issue by NCH550** [QingyongHu/RandLA-Net#46]
请问在test文件夹生成.ply文件之后，应该怎么用hepler_tool.py里面的Plot类可视化他们？（我已经运行main_S3DIS.py的test了）

**Comment by honggesmile** [comment]
> 请问在test文件夹生成.ply文件之后，应该怎么用hepler_tool.py里面的Plot类可视化他们？（我已经运行main_S3DIS.py的test了）

你好，可以交流一下吗，我的微信：vision2d

**Comment by QingyongHu** [comment]
Hi @NCH550, thanks for your interest in our work!

Please find the visualization example code [here](https://github.com/QingyongHu/RandLA-Net/blob/6da2ff60c94233c8754d2e04aba3eda3c4fde360/utils/6_fold_cv.py#L33-L38).

**Comment by KangchengLiu** [comment]
@QingyongHu, could you plese also provide visualization of attention scores?

**Comment by NCH550** [comment]
> Hi @NCH550, thanks for your interest in our work!
> Please find the visualization example code here.

thanks
