### ISSUE TITLE
Question about inference

### ISSUE THREAD

**Issue by coronax1016** [QingyongHu/RandLA-Net#47]
Dear HuQingyong,
I have trained the network with my data. It works perfectly. But I have some problem with the inference. with --mode test. my data have 5 classes and I have set class 0 as ignore in training. And the inference has only 4 labels from 1 to 4. But label 0 is the background label for my class. Which means that I have only 4 probs instead of 5 (include background). How could I fix this?

Many thanks!

**Comment by abhigoku10** [comment]
@coronax1016 hi just to understand since i am facing issues while training which  type of dataset does your custom dataset belong to like semanttick kitti or s3dis ?? what allthe changes you have made while training can you please sharre the information since ia m facing issues #10 
THanks for the support

**Comment by coronax1016** [comment]
sorry, even I use the Semantic3D data or Kitti data. the output always ignores the label 0. Which means the "background" class is missing?

**Comment by abhigoku10** [comment]
@coronax1016 how many classes does your custom data consists of ?? what all changes you made during trianing

**Comment by coronax1016** [comment]
@abhigoku10 I mean even I use the original code for Semantic3D. there are totally of 9 classes that include ignored one (background). For the inference, there is no background class (0).

**Comment by QingyongHu** [comment]
Hi @coronax1016, thanks for your interest in our work!
For your question, the simplest solution is to revise this [line](https://github.com/QingyongHu/RandLA-Net/blob/6da2ff60c94233c8754d2e04aba3eda3c4fde360/main_Semantic3D.py#L29) as:         self.ignored_labels = np.array([])

The points belonging to class '0' would not be ignored in this case.

**Comment by coronax1016** [comment]
@QingyongHu Thanks for the reply. As in this case, the background will also be learned in the network which will significantly affect the coverage speed and result. And also, in the training step, the acc will be very high case the background is more than 90%. And it's hard to know the "true" acc for the network during training.

**Comment by QingyongHu** [comment]
Hi @coronax1016, sorry I really cannot understand your question, do you want to segment the background class or ignored? 
In addition, have you aware that the main evaluation metric in our framework is mean IoU?

**Comment by coronax1016** [comment]
@QingyongHu Sorry for my poor English. I want to segment the background.
I think now I understand what you mean. If I set the ignore label to [0], which will ignore the label 0 for both training and inference, right?

**Comment by QingyongHu** [comment]
@coronax1016. Yes, because the class '0' in Semantic3D and SemanticKITTI denote unclassified or invalid points, so we need to kick these points out when calculating loss. You definitely should not ignore this if class 0 has real meaning in your data.

**Comment by coronax1016** [comment]
@QingyongHu Millions of thanks! I always thought it's my fault to get len(class) - 1 output. 👍
