### ISSUE TITLE
Question about my own test data based on Semantic3D 

### ISSUE THREAD

**Issue by zhang-gang** [QingyongHu/RandLA-Net#49]
@QingyongHu 
Thanks for you sharing the wonderful code!
I have a outdoor test data about 4 million points and run the test on the pre-trained Semantic3D model you provided. By using data_prepare_semantic3d.py, the ply and kpl files can be generated sucessfully.  But the test result is not so good and basically all the points are labled only  with "hard scape'".

Here is the question:  
You do "queried_pc_xyz[:, 0:2] = queried_pc_xyz[:, 0:2] - pick_point[:, 0:2]" and leave Z out. In my test data,  Z value is from 101 to 130. These Z value range are hudge different from the values  in  Semantic3D  dataset.  
Is necessary to normalize coordinate Z value? or any other suggestion?

**Comment by QingyongHu** [comment]
Hi @zhang-gang, thanks for your interest in our work!
I would suggest normalizing the coordinate z in your case.
Good luck!
