### ISSUE TITLE
process the datasets of Semantic3D with 32G ram

### ISSUE THREAD

**Issue by NCH550** [QingyongHu/RandLA-Net#50]
请问32G内存的服务器处理Semantic3D数据集时内存不够，能否通过改代码来解决问题？应该改哪儿？

**Comment by QingyongHu** [comment]
Hi @NCH550,
请问是在data_processing步骤中内存不够还是training过程中内存不够？

**Comment by KangchengLiu** [comment]
How could I prepare and preprocess the Semantic3D dataset with only 16g RAM?
