### ISSUE TITLE
some problems about Semantic3D

### ISSUE THREAD

**Issue by NCH550** [QingyongHu/RandLA-Net#52]
请问Semantic3D数据集跑完test之后没有生成.ply文件只生成了.label文件，我要如何可视化test结果和原始图像呢？

**Comment by QingyongHu** [comment]
直接在这个[地方](https://github.com/QingyongHu/RandLA-Net/blob/6da2ff60c94233c8754d2e04aba3eda3c4fde360/tester_Semantic3D.py#L125)后面加上：

 write_ply(join(test_path, 'predictions', cloud_name), [points, pred], ['x', 'y', 'z', 'pred'])

然后再用 Plot.draw_pc_sem_ins()这个函数就可以了

**Comment by NCH550** [comment]
好的，谢谢！

**Comment by shqfeng** [comment]
> 好的，谢谢！

您好！方便发我一份semantic3d数据的训练模型吗？谢谢
