### ISSUE TITLE
预测点云时间过长

### ISSUE THREAD

**Issue by honggesmile** [QingyongHu/RandLA-Net#55]
@QingyongHu 胡博，你好。现在我拿训练好的模型预测新的点云，预测一个点云大概要20s，把结果可视化显示，效果很棒。但是就是时间有点长，不知道这个时间是否正常.下面是运行的部分结果：
```
加载模型时间:  1.582892894744873
test_path: test/Log_2020-04-14_03-39-11
pre_preds: [0.854312   0.6365489  0.9791355  ... 0.9882188  0.98364115 0.9834389 ]
len(pre_preds): 496232
总时间:  20.12405800819397
```

**Comment by QingyongHu** [comment]
@honggesmile 你好请问你预测用的点云是多大的？此外你每次输入的batch_size以及num_points分别是多少？

**Comment by honggesmile** [comment]
@QingyongHu 你好，胡博。这是我的预测时间和参数的关系。我修改的是help_tool.py里面的参数：
`class ConfigS3DIS:
    k_n = 16  # KNN
    num_layers = 5  # Number of layers
    num_points = 40960  # Number of input points
    num_classes = 13  # Number of valid classes
    sub_grid_size = 0.04  # preprocess_parameter

    # batch_size = 6  # batch_size during training
    # val_batch_size = 20  # batch_size during validation and test
    # train_steps = 500  # Number of steps per epochs
    # val_steps = 100  # Number of validation steps per epoch

    batch_size = 6  # batch_size during training
    val_batch_size = 80  # batch_size during validation and test
    train_steps = 500  # Number of steps per epochs
    val_steps = 100  # Number of validation steps per epoch`
下图是结果：
![Screenshot from 2020-04-16 13-43-03](https://user-images.githubusercontent.com/49434431/79419130-c60b7000-7fe8-11ea-8655-87c587bc07db.png)

**Comment by QingyongHu** [comment]
Hi @honggesmile，数据非常详细，请问这个总时间是每一步的时间，还是加起来的时间？

**Comment by honggesmile** [comment]
加起来一起的时间,就是从导入点云,然后数据处理,预测,最终可视化加起来一起画的时间.

**Comment by QingyongHu** [comment]
Hi @honggesmile,
因为我们方法为了更好的性能在后面还加了voting，因此很多点其实是测了很多遍的，但如果对你自己的数据或者实际应用中这一步并不是必须的，可以尝试直接inference整个点云或者把val_steps减少一些

**Comment by honggesmile** [comment]
好的,我再试试.感谢胡博指导

**Comment by DRosemei** [comment]
Hi@ @honggesmile, I also met this problem and have you made it faster for inferencing?

**Comment by abhigoku10** [comment]
@honggesmile @DRosemei  where you guys able to obtain the faster inference by modification of the code ??

**Comment by honggesmile** [comment]
> Hi@ @honggesmile, I also met this problem and have you made it faster for inferencing?
@DRosemei @abhigoku10 
It has not been resolved yet. It is currently predicted the point cloud that contains 50W points will take 6s at least

**Comment by abhigoku10** [comment]
@honggesmile @DRosemei  i am getting around 1.5 sec for sequence 8 of semantic kitti dataset using the current code. but the author has mentioned around 0.045 sec . how to get this time i am not sure , plsd do suggest if you have any ideas

**Comment by DRosemei** [comment]
> > Hi@ @honggesmile, I also met this problem and have you made it faster for inferencing?
> > @DRosemei @abhigoku10
> > It has not been resolved yet. It is currently predicted the point cloud that contains 50W points will take 6s at least
你好 @honggesmile ，我用了原始的配置文件，然后在main_S3DIS.py中测试时间，发现跑完整个Area1要105s。请问你是怎么设置大约50W个点的呢？我的主机配置和你差不多。
![image](https://user-images.githubusercontent.com/27892562/80166550-d1762100-8610-11ea-98fb-fa59c3cd3bac.png)

**Comment by honggesmile** [comment]
> > > Hi@ @honggesmile, I also met this problem and have you made it faster for inferencing?
> > > @DRosemei @abhigoku10
> > > It has not been resolved yet. It is currently predicted the point cloud that contains 50W points will take 6s at least
> > > 你好 @honggesmile ，我用了原始的配置文件，然后在main_S3DIS.py中测试时间，发现跑完整个Area1要105s。请问你是怎么设置大约50W个点的呢？是通过（总的测试时间/(num_points*val_batch_size*val_steps/50w))来计算的吗？这样算下来，我大概是0.64s(使用2080Ti)
> > > ![image](https://user-images.githubusercontent.com/27892562/80166550-d1762100-8610-11ea-98fb-fa59c3cd3bac.png)

@DRosemei 我是测试单独的一张包含50W个点的点云，然后计算时间的，

**Comment by honggesmile** [comment]
> > > > Hi@ @honggesmile, I also met this problem and have you made it faster for inferencing?
> > > > @DRosemei @abhigoku10
> > > > It has not been resolved yet. It is currently predicted the point cloud that contains 50W points will take 6s at least
> > > > 你好 @honggesmile ，我用了原始的配置文件，然后在main_S3DIS.py中测试时间，发现跑完整个Area1要105s。请问你是怎么设置大约50W个点的呢？是通过（总的测试时间/(num_points_val_batch_size_val_steps/50w))来计算的吗？这样算下来，我大概是0.64s(使用2080Ti)
> > > > ![image](https://user-images.githubusercontent.com/27892562/80166550-d1762100-8610-11ea-98fb-fa59c3cd3bac.png)
> 
> @DRosemei 我是测试单独的一张包含50W个点的点云，然后计算时间的，

@DRosemei 老哥，有兴趣加微信交流一下吗？我：vision2d

**Comment by DRosemei** [comment]
> > > > > Hi@ @honggesmile, I also met this problem and have you made it faster for inferencing?
> > > > > @DRosemei @abhigoku10
> > > > > It has not been resolved yet. It is currently predicted the point cloud that contains 50W points will take 6s at least
> > > > > 你好 @honggesmile ，我用了原始的配置文件，然后在main_S3DIS.py中测试时间，发现跑完整个Area1要105s。请问你是怎么设置大约50W个点的呢？是通过（总的测试时间/(num_points_val_batch_size_val_steps/50w))来计算的吗？这样算下来，我大概是0.64s(使用2080Ti)
> > > > > ![image](https://user-images.githubusercontent.com/27892562/80166550-d1762100-8610-11ea-98fb-fa59c3cd3bac.png)
> > 
> > 
> > @DRosemei 我是测试单独的一张包含50W个点的点云，然后计算时间的，
> 
> @DRosemei 老哥，有兴趣加微信交流一下吗？我：vision2d

ok

**Comment by DRosemei** [comment]
@QingyongHu 您好，我也遇到了同样的问题，并有以下的结果
![image](https://user-images.githubusercontent.com/27892562/80190734-5419d300-8647-11ea-90c8-a293e9181ab8.png)
然后我将num_votes置为1，发现并没有效果提升，请问这个参数是用来做什么的呢？同时感谢你们的工作:)

**Comment by DRosemei** [comment]
> @honggesmile @DRosemei i am getting around 1.5 sec for sequence 8 of semantic kitti dataset using the current code. but the author has mentioned around 0.045 sec . how to get this time i am not sure , plsd do suggest if you have any ideas

Hi @abhigoku10, I found that it would take 1.15s for inferencing millions of points as the paper said. But now I have no access to semantic kitti dataset, so I cannot do experiments.
![image](https://user-images.githubusercontent.com/27892562/80555582-42e41400-8a03-11ea-8795-c35d648e53ca.png)

**Comment by QingyongHu** [comment]
Hi all,
Please refer to this issue #65 for a more detailed explanation

**Comment by LiDaiY** [comment]
你好，请问你是用什么工具可视化的？
