### ISSUE TITLE
Semantic3d prediction

### ISSUE THREAD

**Issue by NCH550** [QingyongHu/RandLA-Net#57]
你好我想问一下，在tester_Semantic3D.py 的第125行后面直接上
write_ply(join(test_path, 'predictions', cloud_name), [points, pred], ['x', 'y', 'z', 'pred'])
之后是可以保存成ply文件了，在他后面也可以直接加 Plot.draw_pc_sem_ins(points,preds)这个函数，确实可以显示结果，但是要等test跑好久之后才能显示，所以想问一下能否像S3DIS的6_fold_cv.py程序里面的方法一样先读取原始ply和test生成的ply文件，然后再显示出原始图与分割后的图，但是我试了一下却没法读取预测的ply文件。
![image](https://user-images.githubusercontent.com/55341904/79298967-406ac000-7f15-11ea-986d-7ba0554f1e5a.png)

**Comment by QingyongHu** [comment]
Hi @NCH550，
你好这样当然是可以的，出现这个错误的原因是在data_processing的时候为了节约内存和存储空间，我写的代码将float16的值存在ply文件中了。在这种情况下，建议你直接读取txt文件，用这个函数DP.load_pc_semantic3d(pc_path)然后前三位就是xyz坐标，详情可以参见data_prepare那个文件。

另外，在visualize的时候，因为semantic3d中的点云数量很大，如果你是用open3D visualize的话，注意不要直接把所有的点放进去visualize，因为这样会很慢而且电脑会很卡，我一般是random取出来100w到200w个点进行visualize, 而且注意要先将label==0的点去掉，因为这些点是invalid的没有意义，你可以参考下下面的代码：

# remove unlabelled points
invalid_idx = np.where(labels == 0)[0]
points_valid = np.delete(points, invalid_idx, axis=0)
colors_valid = np.delete(colors, invalid_idx, axis=0)
labels_valid = np.delete(labels, invalid_idx)
pred_randla_valid = np.delete(pred_randla, invalid_idx)

# random sample a subset for visualization
vis_idx = np.random.choice(len(labels_valid), 2000000)
Plot.draw_pc(np.concatenate([points_valid, colors_valid], axis=-1)[vis_idx, :])
Plot.draw_pc_sem_ins(points_valid[vis_idx, :], labels_valid[vis_idx], color_list)
Plot.draw_pc_sem_ins(points_valid[vis_idx, :], pred_randla_valid[vis_idx], color_list)

**Comment by NCH550** [comment]
> Hi @NCH550，
> 你好这样当然是可以的，出现这个错误的原因是在data_processing的时候为了节约内存和存储空间，我写的代码将float16的值存在ply文件中了。在这种情况下，建议你直接读取txt文件，用这个函数DP.load_pc_semantic3d(pc_path)然后前三位就是xyz坐标，详情可以参见data_prepare那个文件。
> 另外，在visualize的时候，因为semantic3d中的点云数量很大，如果你是用open3D visualize的话，注意不要直接把所有的点放进去visualize，因为这样会很慢而且电脑会很卡，我一般是random取出来100w到200w个点进行visualize, 而且注意要先将label==0的点去掉，因为这些点是invalid的没有意义，你可以参考下下面的代码：
> % remove unlabelled points
> invalid_idx = np.where(labels == 0)[0]
> points_valid = np.delete(points, invalid_idx, axis=0)
> colors_valid = np.delete(colors, invalid_idx, axis=0)
> labels_valid = np.delete(labels, invalid_idx)
> pred_randla_valid = np.delete(pred_randla, invalid_idx)
> % random sample a subset for visualization
> vis_idx = np.random.choice(len(labels_valid), 2000000)
> Plot.draw_pc(np.concatenate([points_valid, colors_valid], axis=-1)[vis_idx, :])
> Plot.draw_pc_sem_ins(points_valid[vis_idx, :], labels_valid[vis_idx], color_list)
> Plot.draw_pc_sem_ins(points_valid[vis_idx, :], pred_randla_valid[vis_idx], color_list)

好的，非常感谢

**Comment by TankyFranky** [comment]
是否可以发布您的文件。(Visualization.py) 我还想可视化我的预测数据。

是否可以發布您的文件。(Visualization.py) 我還想可視化我的預測數據。
