### ISSUE TITLE
Visualization of attention scores in attentive pooling

### ISSUE THREAD

**Issue by KangchengLiu** [QingyongHu/RandLA-Net#58]
@QingyongHu, could you plese also provide visualization of attention scores in attentive pooling of Randlanet as shown in Fig. 8 of the paper?

**Comment by QingyongHu** [comment]
Hi, @KangchengLiu, sorry for my late response.

We have pointed out that the attentive pooling operates on each local neighborhood, that is:
1. It is hardly able to recognize meaningful shapes from such small local regions (K = 16)
2. For an input point cloud, there would be N (N~50K)  attention scores (16*d matrix). It is also not reasonable to use the average attention score. 

 As a workaround, we visualize the learned attention weight matrix. Please refer to the supplementary for details.
