### ISSUE TITLE
TensorRT optimization 

### ISSUE THREAD

**Issue by abhigoku10** [QingyongHu/RandLA-Net#60]
@QingyongHu have you tried to optimise the model using tensorrt or convert the model on to the tensorflow lite version where it can ported easily on embeded devices

**Comment by QingyongHu** [comment]
Hi @abhigoku10, I haven't tried this yet, but you are encouraged to have a try if you are interested! I will consider writing a simple version of this code in the future.

**Comment by abhigoku10** [comment]
@QingyongHu are you trying to optimize the current source code ??

**Comment by QingyongHu** [comment]
Hi @abhigoku10, probably later, I was too busy these days.
