### ISSUE TITLE
if the training can run in windows?or only in ubuntu.thanks.

### ISSUE THREAD

**Issue by zsy-hub** [QingyongHu/RandLA-Net#66]
I want to run this train in windows,and i want find some course about it

**Comment by QingyongHu** [comment]
Hi @zsy-hub. Thanks for your interest in our work.
It should be able to run on windows, but you need to make sure the configuration and the environment is correct, but I will still suggest that you directly run this code in ubuntu

**Comment by zsy-hub** [comment]
> 你好@zsy-hub。谢谢你对我们工作的兴趣。
> 它应该能够在windows上运行，但是您需要确保配置和环境是正确的，但是我仍然建议您直接在ubuntu中运行这段代码

ok,thank you very much.
