### ISSUE TITLE
Ground truth for test set of semantic-KITTI

### ISSUE THREAD

**Issue by KangchengLiu** [QingyongHu/RandLA-Net#72]
Hi qingyong,

The test sets of semanticKITTI (sequence 11-21) do not contain the labels, I want to know how did you get the labels for sequence 11-21 of semanticKITTI for your validation and visualization?

Best

**Comment by longmalongma** [comment]
> The test sets of semanticKITTI (sequence 11-21) do not contain the labels, I want to know how did you get the labels for sequence 11-21 of semanticKITTI for your validation and visualization?

Hi,I have same problem,have you solved it?@Kangcheng
