### ISSUE TITLE
About released results of Area5, S3DIS

### ISSUE THREAD

**Issue by ShiQiu0419** [QingyongHu/RandLA-Net#74]
Hi,

I would like to evaluate the performance of my model based on Area 5 of S3DIS, since your paper did not mention that, I tried to calculate it based on your released results on Google Drive and 6_fold_cv.py script. However, I got some unexpected results: 
![image](https://user-images.githubusercontent.com/17152074/82625633-0766ef00-9c29-11ea-9888-537ef3a558d7.png)
I just wonder whether the problem exists in your released results or my setting? Would you be able to present your detailed numeric results on Area 5?

Thanks a lot.

**Comment by YoungSun3Pan** [comment]
hello, did you get the results of Area5 of S3DIS

**Comment by ShiQiu0419** [comment]
> hello, did you get the results of Area5 of S3DIS

1. I tried their voting results on Google Drive to estimate the results of RandLA-Net on Area5, but have some weired results as the pic shows.

2. For their pretrained models,  the best of voting result is ~62.5% mIoU on Area 5

3. For my self-trained RandLA-Net models, the best of voting result is also ~62.5% mIoU on Area 5.

**Comment by QingyongHu** [comment]
Hi @ShiQiu0419, many thanks for your interest in our work. 

First of all, sorry for my late response. The achieved results shown in the image seem incorrect, instead, a mean IoU score of 62.5% is reasonable. Note that, our RandLA-Net is not aiming to overfit on Area 5, instead, the generalization ability of RandLA-Net is good and it is able to achieve satisfactory 6-fold cross-validation results. You are encouraged to use the pre-trained model we provided in Google drive to get the 6-fold cv results, if you don't want to re-train the network.

I hope this would be useful!

**Comment by ShiQiu0419** [comment]
> Hi @ShiQiu0419, many thanks for your interest in our work.
> 
> First of all, sorry for my late response. The achieved results shown in the image seem incorrect, instead, a mean IoU score of 62.5% is reasonable. Note that, our RandLA-Net is not aiming to overfit on Area 5, instead, the generalization ability of RandLA-Net is good and it is able to achieve satisfactory 6-fold cross-validation results. You are encouraged to use the pre-trained model we provided in Google drive to get the 6-fold cv results, if you don't want to re-train the network.
> 
> I hope this would be useful!

Hi @QingyongHu ,

Thanks for your reply. Although I think there should be something wrong with your trained results of S3DIS on Google Drive, the pre-trained models work well. Much appreciate your excellent work.

**Comment by beihaifusang** [comment]
> Hi @ShiQiu0419, many thanks for your interest in our work.
> 
> First of all, sorry for my late response. The achieved results shown in the image seem incorrect, instead, a mean IoU score of 62.5% is reasonable. Note that, our RandLA-Net is not aiming to overfit on Area 5, instead, the generalization ability of RandLA-Net is good and it is able to achieve satisfactory 6-fold cross-validation results. You are encouraged to use the pre-trained model we provided in Google drive to get the 6-fold cv results, if you don't want to re-train the network.
> 
> I hope this would be useful!

Sorry for continuing on this @QingyongHu .
But cloud you explain how those released model is trained?
There are 6 model provided for S3DIS dataset, i.e. one model for each area. I'm not sure if the model is trained on that area, or is trained on the 5 other areas? e.g. Is model in Area_5 trained on 1,2,3,4,6 areas, or only on the 5th area?

Best regards.
