### ISSUE TITLE
S3DIS数据籍准备的问题

### ISSUE THREAD

**Issue by zcy1065670505** [QingyongHu/RandLA-Net#78]
我按照的方式,使用conda创建了新的环境,也安装了那些库,但是编译也通过了,只是给出了警告,但是.o和,.so文件都生成了,为什么在运行 python utils/data_prepare_s3dis.py的时候,一直报错
Traceback (most recent call last):
  File "utils/data_prepare_s3dis.py", line 24, in <module>
    os.mkdir(original_pc_folder) if not exists(original_pc_folder) else None
FileNotFoundError: [Errno 2] No such file or directory: '/data/S3DIS/original_ply'
后来我手动在RandLA-Net/data/S3DIS/下创建了original_ply和input_0.040文件夹下还是一样的错误,再后来我将 original_pc_folder,sub_pc_folder直接=我的路径并手动创建了这两个文件夹,后来报错
41行:
pc_label = np.concatenate(data_list, 0),至少需要一个array.

**Comment by Ailce8862** [comment]
我也出现了这个问题，不知道如何解决 @QingyongHu

**Comment by Ailce8862** [comment]
> 我按照的方式,使用conda创建了新的环境,也安装了那些库,但是编译也通过了,只是给出了警告,但是.o和,.so文件都生成了,为什么在运行 python utils/data_prepare_s3dis.py的时候,一直报错
> Traceback (most recent call last):
> File "utils/data_prepare_s3dis.py", line 24, in
> os.mkdir(original_pc_folder) if not exists(original_pc_folder) else None
> FileNotFoundError: [Errno 2] No such file or directory: '/data/S3DIS/original_ply'
> 后来我手动在RandLA-Net/data/S3DIS/下创建了original_ply和input_0.040文件夹下还是一样的错误,再后来我将 original_pc_folder,sub_pc_folder直接=我的路径并手动创建了这两个文件夹,后来报错
> 41行:
> pc_label = np.concatenate(data_list, 0),至少需要一个array.

你解决这个问题了吗

**Comment by zcy1065670505** [comment]
> > 我按照的方式,使用conda创建了新的环境,也安装了那些库,但是编译也通过了,只是给出了警告,但是.o和,.so文件都生成了,为什么在运行 python utils/data_prepare_s3dis.py的时候,一直报错
> > Traceback (most recent call last):
> > File "utils/data_prepare_s3dis.py", line 24, in
> > os.mkdir(original_pc_folder) if not exists(original_pc_folder) else None
> > FileNotFoundError: [Errno 2] No such file or directory: '/data/S3DIS/original_ply'
> > 后来我手动在RandLA-Net/data/S3DIS/下创建了original_ply和input_0.040文件夹下还是一样的错误,再后来我将 original_pc_folder,sub_pc_folder直接=我的路径并手动创建了这两个文件夹,后来报错
> > 41行:
> > pc_label = np.concatenate(data_list, 0),至少需要一个array.
> 
> 你解决这个问题了吗

没有，请问你解决了吗

**Comment by zcy1065670505** [comment]
> 我也出现了这个问题，不知道如何解决 @QingyongHu

能否说一下你的配置环境，我的python3.5，tf1.13，cuda10.2，cudnn7.6.5

**Comment by zcy1065670505** [comment]
已解决,需要将python utils/data_prepare_s3dis.py中手动创建original_pc_folder和sub_pc_folder文件夹并将
#os.mkdir(original_pc_folder) if not exists(original_pc_folder) else None
#os.mkdir(sub_pc_folder) if not exists(sub_pc_folder) else None
注释.然后将14行
dataset_path = '/data/S3DIS/Stanford3dDataset_v1.2_Aligned_Version'改为
dataset_path = 'data/S3DIS/Stanford3dDataset_v1.2_Aligned_Version'即可.

**Comment by Ailce8862** [comment]
好的，我试一下，谢谢你


| |
梁攀
|
|
邮箱：liangxiaopan8862@126.com
|

签名由 网易邮箱大师 定制

在2020年06月02日 16:49，zcy1065670505 写道：

已解决,需要将python utils/data_prepare_s3dis.py中手动创建original_pc_folder和sub_pc_folder文件夹并将
#os.mkdir(original_pc_folder) if not exists(original_pc_folder) else None
#os.mkdir(sub_pc_folder) if not exists(sub_pc_folder) else None
注释.然后将14行
dataset_path = '/data/S3DIS/Stanford3dDataset_v1.2_Aligned_Version'改为
dataset_path = 'data/S3DIS/Stanford3dDataset_v1.2_Aligned_Version'即可.

**Comment by wlw-nwafu** [comment]
> 已解决，需要将蟒蛇utils的/ data_prepare_s3dis.py中手动创建original_pc_folder和sub_pc_folder文件夹并将
> ＃os.mkdir（original_pc_folder）如果不存在（original_pc_folder）其他无
> ＃os.mkdir（sub_pc_folder）如果不存在（sub_pc_folder）其他无
> 注释。然后将14行
> dataset_path ='
> /data/S3DIS/Stanford3dDataset_v1.2_Aligned_Version'可替换dataset_path ='data / S3DIS / Stanford3dDataset_v1.2_Aligned_Version'即可。

您好，请问在训练时，有没有遇到epoch里边是空的情况？

**Comment by zcy1065670505** [comment]
能否说具体点
&nbsp;


Chengyu&nbsp;Zhou
zhouchengyu517613@foxmail.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wlw-nwafu"<notifications@github.com&gt;; 
发送时间: 2020年6月12日(星期五) 下午5:35
收件人: "QingyongHu/RandLA-Net"<RandLA-Net@noreply.github.com&gt;; 
抄送: "周城宇"<1065670505@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [QingyongHu/RandLA-Net] S3DIS数据籍准备的问题 (#78)





  
已解决，需要将蟒蛇utils的/ data_prepare_s3dis.py中手动创建original_pc_folder和sub_pc_folder文件夹并将
 ＃os.mkdir（original_pc_folder）如果不存在（original_pc_folder）其他无
 ＃os.mkdir（sub_pc_folder）如果不存在（sub_pc_folder）其他无
 注释。然后将14行
 dataset_path ='
 /data/S3DIS/Stanford3dDataset_v1.2_Aligned_Version'可替换dataset_path ='data / S3DIS / Stanford3dDataset_v1.2_Aligned_Version'即可。
  
您好，请问在训练时，有没有遇到epoch里边是空的情况？

**Comment by wlw-nwafu** [comment]
> 能否说具体点
> &nbsp;
> 
> 
> Chengyu&nbsp;Zhou
> zhouchengyu517613@foxmail.com
> 
> 
> 
> &nbsp;
> …
训练的时候报错ValueError: attempt to get argmin of an empty sequence，训练的epoch下边没有输出信息，就到了下一个epoch，配置我是python3.6，cuda10.0。

**Comment by zcy1065670505** [comment]
数据准备阶段都输出了.ply和.Kdtree文件了吗
&nbsp;


Chengyu&nbsp;Zhou
zhouchengyu517613@foxmail.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wlw-nwafu"<notifications@github.com&gt;; 
发送时间: 2020年6月13日(星期六) 下午3:36
收件人: "QingyongHu/RandLA-Net"<RandLA-Net@noreply.github.com&gt;; 
抄送: "周城宇"<1065670505@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [QingyongHu/RandLA-Net] S3DIS数据籍准备的问题 (#78)





  
能否说具体点
 &nbsp;
 
Chengyu&nbsp;Zhou
 zhouchengyu517613@foxmail.com
 
&nbsp;
 …
 训练的时候报错ValueError: attempt to get argmin of an empty sequence，训练的epoch下边没有输出信息，就到了下一个epoch，配置我是python3.6，cuda10.0。

**Comment by wlw-nwafu** [comment]
> 数据准备阶段都输出了.ply和.Kdtree文件了吗
> &nbsp;
> 
> 
> Chengyu&nbsp;Zhou
> zhouchengyu517613@foxmail.com
> 
> 
> 
> &nbsp;
> …

是的，前几步都对的，正确输出了

**Comment by wlw-nwafu** [comment]
不会是因为配置的原因吧？

**Comment by zcy1065670505** [comment]
你数据准备是按照我说的这种方法修改的吗&nbsp;


Chengyu&nbsp;Zhou
zhouchengyu517613@foxmail.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wlw-nwafu"<notifications@github.com&gt;; 
发送时间: 2020年6月13日(星期六) 下午3:42
收件人: "QingyongHu/RandLA-Net"<RandLA-Net@noreply.github.com&gt;; 
抄送: "周城宇"<1065670505@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [QingyongHu/RandLA-Net] S3DIS数据籍准备的问题 (#78)





 
不会是因为配置的原因吧？

**Comment by wlw-nwafu** [comment]
是的，

**Comment by zcy1065670505** [comment]
那你需要将main_S3DIS.py的16行:self.path='/data/S3DIS'改成
self.path='data/S3DIS'
然后在helper_tool.py中51行将batch_size改成自己显卡能支持的就可以了.
我的是gtx960m 4G,batch_size=2就刚好.
&nbsp;


Chengyu&nbsp;Zhou
zhouchengyu517613@foxmail.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wlw-nwafu"<notifications@github.com&gt;; 
发送时间: 2020年6月13日(星期六) 下午3:56
收件人: "QingyongHu/RandLA-Net"<RandLA-Net@noreply.github.com&gt;; 
抄送: "周城宇"<1065670505@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [QingyongHu/RandLA-Net] S3DIS数据籍准备的问题 (#78)





 
是的，

**Comment by wlw-nwafu** [comment]
> 那你需要将main_S3DIS.py的16行:self.path='/data/S3DIS'改成
> self.path='data/S3DIS'
> 然后在helper_tool.py中51行将batch_size改成自己显卡能支持的就可以了.
> 我的是gtx960m 4G,batch_size=2就刚好.
> &nbsp;
> 
> 
> Chengyu&nbsp;Zhou
> zhouchengyu517613@foxmail.com
> 
> 
> 
> &nbsp;
> …

这个我也尝试了，还是不行。会不会是cuda版本过高了呢？

**Comment by wlw-nwafu** [comment]
> 那你需要将main_S3DIS.py的16行:self.path='/data/S3DIS'改成
> self.path='data/S3DIS'
> 然后在helper_tool.py中51行将batch_size改成自己显卡能支持的就可以了.
> 我的是gtx960m 4G,batch_size=2就刚好.
>  
> Chengyu Zhou
> zhouchengyu517613@foxmail.com
>  
> …
> 
> 这个我也尝试了，还是不行。会不会是cuda版本过高了呢？

非常感谢你的回答

**Comment by zcy1065670505** [comment]
不会吧,我的cuda是10.2,py3.6,tf1.13都可以.
&nbsp;


Chengyu&nbsp;Zhou
zhouchengyu517613@foxmail.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wlw-nwafu"<notifications@github.com&gt;; 
发送时间: 2020年6月13日(星期六) 下午4:08
收件人: "QingyongHu/RandLA-Net"<RandLA-Net@noreply.github.com&gt;; 
抄送: "周城宇"<1065670505@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [QingyongHu/RandLA-Net] S3DIS数据籍准备的问题 (#78)





  
那你需要将main_S3DIS.py的16行:self.path='/data/S3DIS'改成
 self.path='data/S3DIS'
 然后在helper_tool.py中51行将batch_size改成自己显卡能支持的就可以了.
 我的是gtx960m 4G,batch_size=2就刚好.
 &nbsp;
 
Chengyu&nbsp;Zhou
 zhouchengyu517613@foxmail.com
 
&nbsp;
 …
  
这个我也尝试了，还是不行。会不会是cuda版本过高了呢？

**Comment by wlw-nwafu** [comment]
> 不会吧,我的cuda是10.2,py3.6,tf1.13都可以.
> &nbsp;
> 
> 
> Chengyu&nbsp;Zhou
> zhouchengyu517613@foxmail.com
> 
> 
> 
> &nbsp;
> …

那好吧，我在试一试

**Comment by zcy1065670505** [comment]
你这个问题应该是数据问题,要不就是数据没准备好,要不就是数据准备好了,但是送入网络的过程出了问题,没送进去.
&nbsp;


Chengyu&nbsp;Zhou
zhouchengyu517613@foxmail.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wlw-nwafu"<notifications@github.com&gt;; 
发送时间: 2020年6月13日(星期六) 下午4:18
收件人: "QingyongHu/RandLA-Net"<RandLA-Net@noreply.github.com&gt;; 
抄送: "周城宇"<1065670505@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [QingyongHu/RandLA-Net] S3DIS数据籍准备的问题 (#78)





  
不会吧,我的cuda是10.2,py3.6,tf1.13都可以.
 &nbsp;
 
Chengyu&nbsp;Zhou
 zhouchengyu517613@foxmail.com
 
&nbsp;
 …
  
那好吧，我在试一试

**Comment by Mr-Sue** [comment]
![image](https://user-images.githubusercontent.com/50626471/115873003-065fc280-a475-11eb-931c-af6e1786e737.png)

**Comment by hhhhsmx** [comment]
> sub_pc_folder

您好，我通过您这种方式修改后，还是出现原来的文件不存在这种情况，这是什么情况呢
