### ISSUE TITLE
error when running data_prepare_semantickitti.py

### ISSUE THREAD

**Issue by amiltonwong** [QingyongHu/RandLA-Net#8]
Hi, @QingyongHu ,

When I run `python utils/data_prepare_semantickitti.py`, I got the following error after finishing seq00 (000000.bin to 004540.bin) and starting seq01:

```
004536.bin
004537.bin
004538.bin
004539.bin
004540.bin
sequence01 start
000000.bin
000000.npy
Traceback (most recent call last):
  File "utils/data_prepare_semantickitti.py", line 44, in <module>
    sub_points, sub_labels = DP.grid_sub_sampling(points, labels=labels, grid_size=grid_size)
  File "/data/code10/RandLA-Net/helper_tool.py", line 211, in grid_sub_sampling
    return cpp_subsampling.compute(points, classes=labels, sampleDl=grid_size, verbose=verbose)
RuntimeError: Wrong dimensions : classes.shape is not (N,) or (N, d)
```

Any suggestion to fix this issue?

THX!

**Comment by QingyongHu** [comment]
Hi, @amiltonwong, I have tested on my computer just now but it works very smooth, can you please check the data you have download? Maybe there is something wrong with your data.

**Comment by amiltonwong** [comment]
Thanks @QingyongHu , I finally figured it out.

**Comment by abhigoku10** [comment]
@amiltonwong  can you please let us know how did u solve it !!!

**Comment by amiltonwong** [comment]
@abhigoku10 , I download the dataset again. :)
