### ISSUE TITLE
Could you share data about every S3DIS area?

### ISSUE THREAD

**Issue by Syvvvvv** [QingyongHu/RandLA-Net#84]

**Comment by Syvvvvv** [comment]
I reach the mIoU is 67.8. I don't know why it is so low. Is paper's data trained by defualt parameters? 
1 ---- 75.27
2 ---- 53.02
3 ---- 76.66
4 ---- 62.72
5 ---- 61.11
6 ---- 78.14

**Comment by Syvvvvv** [comment]
你好，能分享S3DIS详细的数据吗 @QingyongHu

**Comment by QingyongHu** [comment]
@Syvvvvv 不好意思回复晚了，我们是按照默认的参数进行训练的，对于你的情况多train几次就可以得到更好的结果了。
我们的结果是：
1 ---- 74.54
2 ---- 56.21
3 ---- 78.07
4 ---- 61.96
5 ---- 62.51
6 ---- 80.33

**Comment by Syvvvvv** [comment]
非常感谢分享数据
