### ISSUE TITLE
add  Tensorflow 1.11 into helper_requirements.txt

### ISSUE THREAD

**Issue by hansen7** [QingyongHu/RandLA-Net#91]
Hi, there.

Thanks for sharing this well-organised codes, I guess probably need to add `tensorflow-gpu==1.11` in the `helper_requirements.txt`?

This is probably the reason for #90 ,  since he probably have  installed `tensorflow==1.11` which don't have gpu support :)

**Comment by QingyongHu** [comment]
Hi @hansen7, thanks for your suggestion!

Actually we did this, but it seems to conflict with Github support, hence we finally remove this line in the requirements.

Thanks!
