### ISSUE TITLE
How to change the background color of the visualization image from black colour white colour? 

### ISSUE THREAD

**Issue by longmalongma** [QingyongHu/RandLA-Net#92]
Hi,thanks for your great wok! I think your work is excellent!
![f38aa69d4a4cfd1587bb202649b1f3f](https://user-images.githubusercontent.com/40291722/85379227-1ca7a400-b56e-11ea-8695-3f08e65bcd67.png)
I have visualized  segmentation results on semantickitti, I find the background color of the visualization image is black, but the background color of the visualization image in your paper is white and more elegant. How can I change the background color of the visualization image from black to white?  How to make visual pictures beautiful?
![6357ad4dbb1af986ab703bdca96b082](https://user-images.githubusercontent.com/40291722/85379128-01d52f80-b56e-11ea-8085-55e517ad1eda.png)

**Comment by vikas-shetty** [comment]
@longmalongma 
good to see the results.
even iam trying to use the pretrained model and test it. but not able to
if you are used pretrained model, do let me know how did you succeded to get this output

**Comment by enting8696** [comment]
so how to use pretrained model and semantickitti result
