### ISSUE TITLE
RandLA-Net and NPM3D Benchmark

### ISSUE THREAD

**Issue by code-by-lk** [QingyongHu/RandLA-Net#97]
Firstly, thank you for open-sourcing your work on point cloud segmentation. I have been working to replicate the results published on the NPM3D benchmark ([found here](https://npm3d.fr/paris-lille-3d/114)) but have been difficulty making progress.

There was no mention of NPM3D in the original [arxiv paper](https://arxiv.org/abs/1911.11236) or the recent [CVPR paper](https://openaccess.thecvf.com/content_CVPR_2020/papers/Hu_RandLA-Net_Efficient_Semantic_Segmentation_of_Large-Scale_Point_Clouds_CVPR_2020_paper.pdf), so I used the Semantic3D example files (_main_Semantic3D.py_, _tester_Semantic3D.py_) as the starting point.

The configuration parameters (i.e. batch size, points per batch, k neighbours, etc.) in _helper_tools.py_ were kept the same, but the number of classes (9) was updated to match NPM3D. Otherwise, NPM3D .ply files were imported following a similar approach to KPConv and everything else was kept. An initial training run of 50 epochs led to mIoU of 40%, but the test result shows the model randomly assigning class values to points along the segment (shown below). 

![image](https://user-images.githubusercontent.com/35929153/86288629-767c1f80-bba7-11ea-936d-d1564157990d.png)

Is there an obvious mistake in my implementation that might have caused this random assignment of classes? If not, were the model or hyperparameters changed at all to train on NPM3D?

Thanks in advance.

**Comment by QingyongHu** [comment]
Hi @code-by-lk, thanks for your interest in our work!

Yes, we have a quick try of our RandLA-Net on the NPM3D dataset (with the same hyperparameter), the results are much higher than 40% actually. However, I have no idea what is the problem based on your information here. It seems that the qualitative results are dirty and messy...

We plan to release the code on other datasets, including ScanNet, Toronto-3D, DALES, and NPM3D in the future, please stay tuned.

**Comment by code-by-lk** [comment]
Hello @QingyongHu,

Thank you for your response. I will review my implementation as the problem must be related to the changes I made. I look forward to seeing the results on the other datasets.

**Comment by Yacovitch** [comment]
Hello @QingyongHu,

Do you mind sharing with us the code on DALES? I am trying to reproduce the performance that you posted on SQN.

**Comment by QingyongHu** [comment]
@Yacovitch Thanks for your interest in our work!

Sorry I am rather overloaded this week, I will do my best to commit the code on the DALES to the repo before next week.

Thanks for your understanding!

Best,

**Comment by Yacovitch** [comment]
@QingyongHu

Hi there, I guess you are very busy.
Is it possible to get any updates on the code on the DALES?

Best,
