### ISSUE TITLE
Understanding the voting logic

### ISSUE THREAD

**Issue by beihaifusang** [QingyongHu/RandLA-Net#98]
Hi @QingyongHu , 

thanks for the great work and open-sourcing it. I'm reading your code and find a bit difficult to understand the voting logic used in ModelTester.

Specifically, it seems the testing will finish as long as 
`if last_min + 4 < new_min:`
Then, what's the point of having a loop of `while last_min < num_votes:` ?

So, could you help explain what's the underlying logic here? I'm guessing the `num_votes` is just a big number to keep the loop going; but `last_min + 4 < new_min` depends on the `delta` calculated in the dataset generator and would be added to the `min_possibility` and `possibility` every time a sub-point-cloud is sampled. Actually, why do you set the number to be `4`? And, roughly how many times of inference would be done on a single point given your way of updating the possibility?

Best regards,
Liyao Tang

**Comment by QingyongHu** [comment]
Hi @beihaifusang. Sorry for my late response, many thanks for your interest in our work!

Actually this is just a hyperparameter and does not need to be 4, it can be 1,2,3 or any other number (I don't think the performance would have significant difference). As you mentioned, what we want to do is to ensure that each point has been evaluated.

I have no idea how many times of inference has been done for each point, but it should be different for each point. On the other hand, we also tried to inference the whole point cloud at a single pass (that means no voting scheme), the proposed network can also achieve satisfactory performance. Also, please refer to this issue #11 to have a more clear idea about the possibility

**Comment by beihaifusang** [comment]
I see. Thanks for the reply!

**Comment by v-shetty** [comment]
@beihaifusang 
correct me if iam wrong
if last_min + 4 < new_min:
i dont know from where did you get this line.

does it related to epoch > 0.5   condtion?

**Comment by v-shetty** [comment]
> Hi @beihaifusang. Sorry for my late response, many thanks for your interest in our work!
> 
> Actually this is just a hyperparameter and does not need to be 4, it can be 1,2,3 or any other number (I don't think the performance would have significant difference). As you mentioned, what we want to do is to ensure that each point has been evaluated.
> 
> I have no idea how many times of inference has been done for each point, but it should be different for each point. On the other hand, we also tried to inference the whole point cloud at a single pass (that means no voting scheme), the proposed network can also achieve satisfactory performance. Also, please refer to this issue #11 to have a more clear idea about the possibility

@QingyongHu where i can change the hyperparameter?

**Comment by beihaifusang** [comment]
> @beihaifusang
> correct me if iam wrong
> if last_min + 4 < new_min:
> i dont know from where did you get this line.
> 
> does it related to epoch > 0.5 condtion?

It's in tester_Semantic3D.py

**Comment by v-shetty** [comment]
> > @beihaifusang
> > correct me if iam wrong
> > if last_min + 4 < new_min:
> > i dont know from where did you get this line.
> > does it related to epoch > 0.5 condtion?
> 
> It's in tester_Semantic3D.py

Thank you for you replay.

Iam focused on tester_semanticKitti.py 
How does the voting works in SemanticKitti ?

if np.min(dataset.min_possibility) > 0.5
 Above line is from tester_SemanticKITTI.py
can you tell me why 0.5?
and can we change it to other values for better speed in inference?
